addons:
  apt:
    packages:
      - autoconf
      - autogen
      - automake
      - build-essential
      - git
      - libncurses5-dev
      - libtool
      - texinfo
script:
  - env VERSION=$TRAVIS_BRANCH bash build-emacs.sh